# Generated by Django 3.2.11 on 2022-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deck_flashcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('Task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
