# Generated by Django 3.2.11 on 2022-01-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
